site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
n_steps:
  description: Number of time steps
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 1.0
    range:
      min: 1.0
      max: 31536000.0
    units: s
pixel_file:
  description: Monitored pixel/grid file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
DEM_file:
  description: RiverTools grid file containing DEM
  value:
    type: file
    default: default_DEM.rtg
    files:
    - default_DEM.rtg
A_units:
  description: Base unit for grid area
  value:
    type: choice
    default: meters
    choices:
    - meters
    - kilometers
LINK_FLATS:
  description: Link flats?
  value:
    type: choice
    default: 'Yes'
    choices:
    - 'Yes'
    - 'No'
FILL_PITS_IN_Z0:
  description: Fill pits in original DEM?
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
LR_PERIODIC:
  description: Use periodic left-right boundary conditions?
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
TB_PERIODIC:
  description: Use periodic top-bottom boundary conditions?
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'

