site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
n_steps:
  description: Number of time steps
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1.0
      max: 31536000.0
    units: s
pixel_file:
  description: Monitored pixel/grid file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
code_file:
  description: RiverTools grid file of D8 flow codes
  value:
    type: file
    default: default_flow.rtg
    files:
    - default_flow.rtg
slope_file:
  description: RiverTools grid file of D8 slopes
  value:
    type: file
    default: default_slope.rtg
    files:
    - default_slope.rtg
MANNING:
  description: Option to use mannings n for roughness
  value:
    type: int
    default: 0
    range:
      min: 0
      max: 1
    units: '-'
LAW_OF_WALL:
  description: Option to use law of wall for roughness
  value:
    type: int
    default: 0
    range:
      min: 0
      max: 1
    units: '-'
nval_ptype:
  description: "Mannings n value"
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
nval_dtype:
  description: "Manning's n value data type"
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
nval:
  description: "Mannings n value"
  value:
    type: float
    default: 0.1
    range:
      min: 0.0
      max: 5.0
    units: s/m^(1/3)
z0val_ptype:
  description: "Law-of-wall roughness values"
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
z0val_dtype:
  description: "Law-of-wall roughness value data type"
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
z0val:
  description: "Law-of-wall roughness value"
  value:
    type: float
    default: 0.1
    range:
      min: 0.0
      max: 5.0
    units: "m"
width_ptype:
  description: Bed width of trapezoid cross-section
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
width_dtype:
  description: Bed width of trapezoid cross-section data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
width:
  description: Scalar value
  value:
    type: float
    default: 10.0
    range:
      min: 0.0
      max: 1E4
width_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
angle_ptype:
  description: Bank angle of trapezoid cross-section
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: deg
angle_dtype:
  description: Bank angle of trapezoid cross-section data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
angle:
  description: Scalar value
  value:
    type: float
    default: 1.0
    range:
      min: 0.0
      max: 360.0
angle_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
d0_ptype:
  description: Initial flow depth
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
d0_dtype:
  description: Initial flow depth data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
d0:
  description: Scalar value
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 0.0
d0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
sinu_ptype:
  description: Absolute channel sinuosity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m m-1
sinu_dtype:
  description: Absolute channel sinuosity data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
sinu:
  description: Scalar value
  value:
    type: float
    default: 1.0
    range:
      min: 0.0
      max: 3.0
sinu_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'

