run_duration:
  description: Simulation run time
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: s
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1
      max: 31536000.0
    units: s
rti_file:
  description: RiverTools info file
  value:
    type: file
    default: default.rti
    files:
    - default.rti
pixel_file:
  description: Monitored pixel/grid file (outlets)
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ks_0_ptype:
  description: Saturated hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ks_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 7.2e-06
    range:
      min: 1E-8
      max: 1E-0
Ks_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ki_0_ptype:
  description: Initial hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ki_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-6
    range:
      min: 1E-8
      max: 1E-0
Ki_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qs_0_ptype:
  description: Saturated soil water content
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qs_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.485
    range:
      min: 0.0
      max: 1.0
qs_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qi_0_ptype:
  description: Initial soil water content (< theta_sat)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qi_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.375
    range:
      min: 0.0
      max: 1.0
qi_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
G_0_ptype:
  description: Capillary length scale
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
G_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.725
    range:
      min: 0.0
      max: 1.0
G_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
gam_0_ptype:
  description: Smith-Parlange parameter
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
gam_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.8
    range:
      min: 0.0
      max: 1.0
gam_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
soil_ptype_0:
  description: Closest standard soil type
  value:
    type: choice
    default: Sand
    choices:
    - Sand
    - Loamy Sand
    - Sandy Loam
    - Silty Loam
    - Loam
    - Sandy Clay Loam
    - Silty Clay Loam
    - Clay Loam
    - Sandy Clay
    - Silty Clay
    - Clay
    units: '-'

