run_duration:
  description: Simulation run time
  value:
    type: int
    default: 3600
    range:
      min: 0
      max: 3153600000
    units: s
n_layers:
  description: Number of soil layers
  value:
    type: int
    default: '1'
    range:
      min: '1'
      max: '3'
    units: '-'
dt:
  description: Timestep for infiltration process
  value:
    type: float
    default: '60.000'
    range:
      min: '0'
      max: 1e3
    units: s
rti_file:
  description: RiverTools info file
  value:
    type: file
    default: default.rti
    files:
    - default.rti
pixel_file:
  description: Monitored pixel/grid file (outlets)
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ks_val_0_ptype:
  description: Saturated hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ks_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ks_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ki_val_0_ptype:
  description: Initial hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ki_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ki_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qs_val_0_ptype:
  description: Saturated soil water content
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qs_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qs_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qi_val_0_ptype:
  description: Initial soil water content (< theta_sat)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qi_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qi_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qr_val_0_ptype:
  description: Residual soil water content (< theta_init)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qr_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qr_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pB_val_0_ptype:
  description: Bubbling pressure head
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pB_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pB_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pA_val_0_ptype:
  description: Pressure head offset parameter
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pA_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pA_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
lam_val_0_ptype:
  description: Pore size distribution
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
lam_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
lam_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
c_val_0_ptype:
  description: Trans. brooks-corey curvature
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
c_val_0_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
c_val_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
dz_val_0:
  description: Vertical distance between nodes
  value:
    type: float
    default: '0.1'
    range:
      min: '0'
      max: 1e3
    units: m
nz_val_0:
  description: Number of vertical layer
  value:
    type: int
    default: '3'
    range:
      min: '1'
      max: '20'
    units: '-'
type_of_soil_layer_0:
  description: Closest standard soil type
  value:
    type: choice
    default: sand
    choices:
    - sand
    - loamy_sand
    - sandy_loam
    - silty_loam
    - loam
    - sandy_clay_loam
    - silty_clay_loam
    - clay_loam
    - sandy_clay
    - silty_clay
    - clay
    units: '-'
Ks_val_1_ptype:
  description: Saturated hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ks_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ks_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ki_val_1_ptype:
  description: Initial hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ki_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ki_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qs_val_1_ptype:
  description: Saturated soil water content
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qs_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qs_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qi_val_1_ptype:
  description: Initial soil water content (< theta_sat)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qi_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qi_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qr_val_1_ptype:
  description: Residual soil water content (< theta_init)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qr_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qr_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pB_val_1_ptype:
  description: Bubbling pressure head
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pB_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pB_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pA_val_1_ptype:
  description: Pressure head offset parameter
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pA_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pA_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
lam_val_1_ptype:
  description: Pore size distribution
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
lam_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
lam_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
c_val_1_ptype:
  description: Trans. brooks-corey curvature
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
c_val_1_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
c_val_1_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
dz_val_1:
  description: Vertical distance between nodes
  value:
    type: float
    default: '0.1'
    range:
      min: '0'
      max: 1e3
    units: m
nz_val_1:
  description: Number of vertical layer
  value:
    type: int
    default: '3'
    range:
      min: '1'
      max: '20'
    units: '-'
type_of_soil_layer_1:
  description: Closest standard soil type
  value:
    type: choice
    default: sand
    choices:
    - sand
    - loamy_sand
    - sandy_loam
    - silty_loam
    - loam
    - sandy_clay_loam
    - silty_clay_loam
    - clay_loam
    - sandy_clay
    - silty_clay
    - clay
    units: '-'
Ks_val_2_ptype:
  description: Saturated hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ks_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ks_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ki_val_2_ptype:
  description: Initial hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ki_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 5E-5
    range:
      min: 1E-8
      max: 1E-0
Ki_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qs_val_2_ptype:
  description: Saturated soil water content
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qs_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qs_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qi_val_2_ptype:
  description: Initial soil water content (< theta_sat)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qi_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qi_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qr_val_2_ptype:
  description: Residual soil water content (< theta_init)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qr_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
qr_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pB_val_2_ptype:
  description: Bubbling pressure head
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pB_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pB_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
pA_val_2_ptype:
  description: Pressure head offset parameter
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
pA_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
pA_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
lam_val_2_ptype:
  description: Pore size distribution
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
lam_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
lam_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
c_val_2_ptype:
  description: Trans. brooks-corey curvature
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
c_val_2_scalar:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 1.0
c_val_2_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
dz_val_2:
  description: Vertical distance between nodes
  value:
    type: float
    default: '0.1'
    range:
      min: '0'
      max: 1e3
    units: m
nz_val_2:
  description: Number of vertical layer
  value:
    type: int
    default: '3'
    range:
      min: '1'
      max: '20'
    units: '-'
type_of_soil_layer_2:
  description: Closest standard soil type
  value:
    type: choice
    default: sand
    choices:
    - sand
    - loamy_sand
    - sandy_loam
    - silty_loam
    - loam
    - sandy_clay_loam
    - silty_clay_loam
    - clay_loam
    - sandy_clay
    - silty_clay
    - clay
    units: '-'

