site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
n_steps:
  description: Number of time steps
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1.0
      max: 31536000.0
    units: s
pixel_file:
  description: Monitored pixel/grid file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
K_soil_ptype:
  description: Thermal conductivity of soil
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: W m-1 degC-1
K_soil_dtype:
  description: Thermal conductivity of soil data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
K_soil:
  description: Scalar value
  value:
    type: float
    default: 0.45
    range:
      min: 0.0
      max: 100.0
K_soil_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
soil_x_ptype:
  description: Soil reference depth
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
soil_x_dtype:
  description: Soil reference depth data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
soil_x:
  description: Scalar value
  value:
    type: float
    default: 0.05
    range:
      min: 0.0
      max: 10.0
soil_x_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
T_soil_x_ptype:
  description: Temperature of soil at reference depth
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: degC
T_soil_x_dtype:
  description: Temperature of soil at reference depth data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
T_soil_x:
  description: Scalar value
  value:
    type: float
    default: 0.0
    range:
      min: -100.0
      max: 50.0
T_soil_x_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'

