site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1.0
      max: 31536000.0
    units: s
use_sources:
  description: Option to use sources
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
source_file:
  description: Source information file
  value:
    type: file
    default: 'off'
    files:
    - site_source.txt
    - 'off'
use_sinks:
  description: Option to use sinks
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
sink_file:
  description: Sink information file
  value:
    type: file
    default: 'off'
    files:
    - site_sink.txt
    - 'off'
use_canals:
  description: Option to use canals
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
canal_file:
  description: Canal information file
  value:
    type: file
    default: 'off'
    files:
    - site_canal.txt
    - 'off'

