site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
n_steps:
  description: Number of time steps
  value:
    type: int
    default: 100
    range:
      min: 1
      max: 100000
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 600
    range:
      min: 1
      max: 31536000
    units: s
pixel_file:
  description: Monitored pixel/grid file (outlets)
  value:
    type: file
    default: 'off'
    files:
    - 'off'
rho_snow_ptype:
  description: Density of snow
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: kg m-3
rho_snow_dtype:
  description: Density of snow data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
rho_snow:
  description: Scalar value
  value:
    type: float
    default: 300.0
    range:
      min: 0.0
      max: 1e3
rho_snow_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
c0_ptype:
  description: Degree day coefficient
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: mm d-1 degC-1
c0_dtype:
  description: Degree day coefficient data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
c0:
  description: Scalar value
  value:
    type: float
    default: 2.7
    range:
      min: 0.0
      max: 1e2
c0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
T0_ptype:
  description: Reference temperature
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: degC
T0_dtype:
  description: Reference temperature data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
T0:
  description: Scalar value
  value:
    type: float
    default: -0.2
    range:
      min: -100.0
      max: 100
T0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
h0_snow_ptype:
  description: Depth of snow
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
h0_snow_dtype:
  description: Depth of snow data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
h0_snow:
  description: Scalar value
  value:
    type: float
    default: 0.5
    range:
      min: 0.0
      max: 20.0
h0_snow_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
h0_swe_ptype:
  description: Depth of snow water equivalent (SWE)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
h0_swe_dtype:
  description: Depth of snow water equivalent (SWE) snow data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
h0_swe:
  description: Scalar value
  value:
    type: float
    default: 0.15
    range:
      min: 0.0
      max: 20.0
h0_swe_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'

